decks = {
    "gearpunk": [
        ["uranium_purifier", 8],
        ["gearpunk_factory", 4],
        ["city_module", 1],
        ["bomb_engine", 1],
        ["command_pod", 1],
        ["igor_mechanic_elect", 1],
        ["arachnohulk", 4],
        ["axe_suit", 4],
        ["gyropike", 4],
        ["pistoleer", 4],
        ["shield_suit", 4],
        ["visionary_engineer", 4],
        ["mine", 20],
    ],
    "dryad": [
        ["forest", 24],
        ["ancestors_legacy", 4],
        ["blight_thrower", 4],
        ["gliderkin", 4],
        ["hardwood_bludgeon", 4],
        ["lithekin", 4],
        ["overtaking_overgrowth", 4],
        ["the_woods_are_alive", 4],
        ["vine_master", 4],
        ["garnak", 1],
        ["atashi_one_with_all", 1],
        ["primordial_tree", 1],
        ["the_flowering", 1],
    ],
    "ice": [
        ["roost", 24],
        ["blue_drake", 4],
        ["frost_elder", 4],
        ["hatching_season", 4],
        ["ice_ancient", 4],
        ["ice_storm", 4],
        ["kidnap", 4],
        ["treasure_hoard", 4],
        ["unwinged", 4],
        ["dead_of_winter", 3],
        ["fjolnir", 1],
    ],
    "minotaur": [
        ["mine", 20],
        ["uranium_purifier", 8],
    ]
}
